/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hexilization;

import java.awt.Point;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author DayanDey
 */
public class Aplikacja extends javax.swing.JFrame {

    /**
     * Creates new form Aplikacja
     */
    public Aplikacja() {
        heksy = new HashMap<String, Heks>();
        initComponents();
    }
    
 //   private ArrayList<Heks> heksy = new ArrayList<Heks>(); 
    
    private Map<String, Heks> heksy;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pnl_main = new javax.swing.JPanel();
        Btn_Start = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 900));
        setResizable(false);
        setSize(new java.awt.Dimension(200, 180));

        Btn_Start.setText("Start");
        Btn_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_StartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_mainLayout = new javax.swing.GroupLayout(Pnl_main);
        Pnl_main.setLayout(Pnl_mainLayout);
        Pnl_mainLayout.setHorizontalGroup(
            Pnl_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_mainLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Btn_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(824, Short.MAX_VALUE))
        );
        Pnl_mainLayout.setVerticalGroup(
            Pnl_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_mainLayout.createSequentialGroup()
                .addContainerGap(443, Short.MAX_VALUE)
                .addComponent(Btn_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(299, 299, 299))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pnl_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pnl_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_StartActionPerformed
        this.Btn_Start.setVisible(false); 
        
    //    Stwórz_Strukture_Heksów();
        
        RysujHeksy();
    }//GEN-LAST:event_Btn_StartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplikacja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplikacja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplikacja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplikacja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplikacja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Start;
    private javax.swing.JPanel Pnl_main;
    // End of variables declaration//GEN-END:variables

    private void RysujHeks(int x, int y) 
    {        
        Heks nowy = new Heks();  
        nowy.set_id(nowy_id());
        heksy.put(nowy.get_id(),nowy);         
        nowy.set_location(new Point(x,y));
        nowy.rysuj(this.Pnl_main);
    }
    
     private void RysujHeks(int i, Heks stary) 
    {  
        Heks nowy = new Heks();
        nowy.set_id(nowy_id());
        heksy.put(nowy.get_id(),nowy); 
        stary.set_neightbour(nowy, i);
        nowy.rysuj(Pnl_main); 
    }
     
    private String najnowszyheks = "";
    
    private String nowy_id()
    {
        najnowszyheks = "id_"+heksy.size()+"";
        return najnowszyheks;
    }

    private void RysujHeksy() {
        
    //    Point pkt = new Point((this.getWidth()/2)-50,(this.getHeight()/2)-50);   
        Point pkt = new Point(300,0);   
        RysujHeks(pkt.x,pkt.y);  
        
        for(int j=0;j<9;j++)
        {
            for(int i=0;i<9+j;i++)
            {
                if(j%2==0)
                {
                    RysujHeks(5, heksy.get(najnowszyheks));  
                }
                else
                {
                    RysujHeks(2, heksy.get(najnowszyheks));                  
                }                                 
            }
          
        
            RysujHeks(j%2, heksy.get(najnowszyheks));    
        }
        
        for(int j=0;j<8;j++)
        {
            for(int i=17;i>0+j;i--)
            {
                if(j%2==1)
                {
                    RysujHeks(5, heksy.get(najnowszyheks));  
                }
                else
                {
                    RysujHeks(2, heksy.get(najnowszyheks));                  
                }                                 
            }
          
            if(j!=7)
            RysujHeks(j%2, heksy.get(najnowszyheks));    
        }
    }

    private void Stwórz_Strukture_Heksów() 
    {
          
        Heks nowy = Nowy_heks();
        nowy.set_location(new Point(300,0));
        nowy.set_neightbour(Nowy_heks(), 5);//tu skończyłem
        //grafy?
    }
    
    private Heks Nowy_heks()
    {
        Heks nowy = new Heks();  
        nowy.set_id(nowy_id());
        heksy.put(nowy.get_id(),nowy);       
        return nowy;
    }
}
